import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Open_Sans, Prata } from "next/font/google";
import "./globals.css";
import '@/public/css/open-iconic-bootstrap.min.css';
// import '@/public/css/animate.css';
import '@/public/css/owl.carousel.min.css';
import '@/public/css/owl.theme.default.min.css';
import '@/public/css/magnific-popup.css';
import '@/public/css/aos.css';
import '@/public/css/icomoon.css';
import '@/public/css/bootstrap-datepicker.css';
import '@/public/css/jquery.timepicker.css';


import '@/public/css/flaticon.css';
import '@/public/css/icomoon.css';
import '@/public/css/style.css';

import { cn } from "@/lib/utils";
import Script from "next/script";

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const openSans = Open_Sans({
  weight: ['300', '400', '600'],
  variable: "--font-open-sans",
  subsets: ["latin"],
});

const prata = Prata({
  variable: "--font-prata",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", openSans.variable, prata.variable, "font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col">
        <nav className="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
          <div className="container">
            <a className="navbar-brand" href="index.html"><span className="flaticon-lotus"></span>Energen</a>
            <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
              aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
              <span className="oi oi-menu"></span> Menu
            </button>
            <div className="collapse navbar-collapse" id="ftco-nav">
              <ul className="navbar-nav ml-auto">
                <li className="nav-item active"><a href="#" className="nav-link">Home</a></li>
                <li className="nav-item"><a href="#treatments" className="nav-link">Treatments</a></li>
                <li className="nav-item"><a href="#pricing" className="nav-link">Pricing</a></li>
                <li className="nav-item"><a href="/blogs" className="nav-link">Blog</a></li>
                <li className="nav-item"><a href="/contact" className="nav-link">Contact</a></li>
              </ul>
            </div>
          </div>
        </nav>
        {/* // end nav */}
        {children}
        <footer className="ftco-footer ftco-section">
          <div className="container">
            <div className="row d-flex">
              <div className="col-md">
                <div className="ftco-footer-widget mb-4">
                  <h2 className="ftco-heading-2">Energen</h2>
                  <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia,
                    there live the blind texts.</p>
                  <ul className="ftco-footer-social list-unstyled float-lft mt-3">
                    <li className=" "><a href="#"><span className="icon-twitter"></span></a></li>
                    <li className=" "><a href="#"><span className="icon-facebook"></span></a></li>
                    <li className=" "><a href="#"><span className="icon-instagram"></span></a></li>
                  </ul>
                </div>
              </div>
              <div className="col-md">
                <div className="ftco-footer-widget mb-4 ml-md-4">
                  <h2 className="ftco-heading-2">Popular Links</h2>
                  <ul className="list-unstyled">
                    <li><a href="#">Aromatheraphy</a></li>
                    <li><a href="#">Skin Care</a></li>
                    <li><a href="#">Herbal Spa</a></li>
                    <li><a href="#">Body Massage</a></li>
                  </ul>
                </div>
              </div>
              <div className="col-md">
                <div className="ftco-footer-widget mb-4">
                  <h2 className="ftco-heading-2">Quick Links</h2>
                  <ul className="list-unstyled">
                    <li><a href="#">About</a></li>
                    <li><a href="#">Our Spa</a></li>
                    <li><a href="#">Treatments</a></li>
                    <li><a href="#">Specialists</a></li>
                    <li><a href="#">Contact</a></li>
                  </ul>
                </div>
              </div>
              <div className="col-md">
                <div className="ftco-footer-widget mb-4">
                  <h2 className="ftco-heading-2">Have a Questions?</h2>
                  <div className="block-23 mb-3">
                    <ul>
                      <li><span className="icon icon-map-marker"></span><span className="text">203 Fake St. Mountain
                        View, San Francisco, California, USA</span></li>
                      <li><a href="#"><span className="icon icon-phone"></span><span className="text">+2 392 3929
                        210</span></a></li>
                      <li><a href="#"><span className="icon icon-envelope"></span><span
                        className="text">info@yourdomain.com</span></a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </footer>
        <Script src="/js/jquery.min.js" />
        <Script src="/js/jquery-migrate-3.0.1.min.js" />
        <Script src="/js/popper.min.js" />
        <Script src="/js/bootstrap.min.js" />
        <Script src="/js/jquery.easing.1.3.js" />
        <Script src="/js/jquery.waypoints.min.js" />
        <Script src="/js/jquery.stellar.min.js" />
        <Script src="/js/owl.carousel.min.js" />
        <Script src="/js/jquery.magnific-popup.min.js" />
        <Script src="/js/aos.js" />
        <Script src="/js/jquery.animateNumber.min.js" />
        <Script src="/js/bootstrap-datepicker.js" />
        <Script src="/js/jquery.timepicker.min.js" />
        <Script src="/js/scrollax.min.js" />
        <Script src="/js/main.js" />
      </body>
    </html>
  );
}
